"""Add AI analysis fields to posts and comments

Revision ID: fd98f3303699
Revises: 074abdc261d5
Create Date: 2025-07-12 23:14:52.073340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd98f3303699'
down_revision: Union[str, Sequence[str], None] = '074abdc261d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('ai_analysis', sa.JSON(), nullable=True))
    op.add_column('comments', sa.Column('moderation_score', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('sentiment_score', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('is_ai_processed', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('ai_analysis', sa.JSON(), nullable=True))
    op.add_column('posts', sa.Column('moderation_score', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('sentiment_score', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('content_summary', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('is_ai_processed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_ai_processed')
    op.drop_column('posts', 'content_summary')
    op.drop_column('posts', 'sentiment_score')
    op.drop_column('posts', 'moderation_score')
    op.drop_column('posts', 'ai_analysis')
    op.drop_column('comments', 'is_ai_processed')
    op.drop_column('comments', 'sentiment_score')
    op.drop_column('comments', 'moderation_score')
    op.drop_column('comments', 'ai_analysis')
    # ### end Alembic commands ###
